# Known requirements per distro, please expand if you encounter breakage
known_distros:
  - Arch Linux
  - CentOS
  - Debian
  - Fedora
  - Red Hat Enterprise Linux
  - Ubuntu

debian_deps:
  - build-essential
  - file
  - gawk
  - gettext
  - git
  - libncurses5-dev
  - libssl-dev
  - npm
  - python
  - subversion
  - systemtap-sdt-dev
  - time
  - unzip
  - zlib1g-dev
  - curl

centos_deps:
  - binutils
  - bison
  - bzip2
  - flex
  - gawk
  - gcc
  - gcc-c++
  - gettext
  - git-core
  - glibc
  - glibc-devel
  - glibc-static
  - intltool
  - libselinux-python
  - make
  - ncurses-devel
  - ncurses-libs
  - npm
  - openssl-devel
  - patch
  - perl-ExtUtils-MakeMaker
  - quilt
  - sdcc
  - sed
  - sharutils
  - subversion
  - systemtap-sdt-devel
  - time
  - unzip
  - wget
  - xz
  - zlib-devel
  - zlib-static
  - curl

ubuntu_deps:
  - build-essential
  - flex
  - gawk
  - gcc-multilib
  - gettext
  - git-core
  - libncurses5-dev
  - libssl-dev
  - npm
  - subversion
  - systemtap-sdt-dev
  - time
  - unzip
  - zlib1g-dev
  - curl

fedora_deps:
  - binutils
  - bison
  - bzip2
  - flex
  - gawk
  - gcc
  - gcc-c++
  - gettext
  - git-core
  - glibc
  - glibc-devel
  - glibc-static
  - intltool
  - libselinux-python
  - make
  - ncurses-compat-libs
  - ncurses-devel
  - npm
  - openssl-devel
  - patch
  - perl-ExtUtils-MakeMaker
  - perl-Thread-Queue
  - quilt
  - sdcc
  - sed
  - sharutils
  - subversion
  - systemtap-sdt-devel
  - time
  - unzip
  - wget
  - zlib-devel
  - zlib-static
  - curl

arch_deps:
  - automake
  - binutils
  - bison
  - bzip2
  - flex
  - gawk
  - gcc
  - gcc-libs
  - gettext
  - git
  - glibc
  - intltool
  - ncurses
  - npm
  - openssl
  - patch
  - perl
  - quilt
  - sdcc
  - sed
  - sharutils
  - subversion
  - systemtap
  - time
  - unzip
  - wget
  - zlib
  - curl
