---
# Builds the more sensitive and dynamic parts of the firmware root configuration
# for example ssh keys are inserted in this role

- name: Create Dropbear folder
  file:
    path: "{{source_dir}}/files/etc/dropbear/"
    state: directory

- name: Add keys to login
  lineinfile:
    dest: "{{source_dir}}/files/etc/dropbear/authorized_keys"
    line: "{{item}}"
    state: present
    create: yes
  with_items: "{{keys_to_insert}}"
  when: insert_keys

- name: Authorized keys only readable by owner
  file:
    path: "{{source_dir}}/files/etc/dropbear/authorized_keys"
    mode: 0600
  when: insert_keys

- name: Create the UCI config folder
  file:
    path: "{{source_dir}}/files/etc/config/"
    state: directory

- name: Template dropbear config
  template:
    src: "dropbear.j2"
    dest: "{{source_dir}}/files/etc/config/dropbear"

- name: Template firewall config
  template:
    src: "firewall.j2"
    dest: "{{source_dir}}/files/etc/config/firewall"

- name: Template DHCP config
  template:
    src: "dhcp.j2"
    dest: "{{source_dir}}/files/etc/config/dhcp"

- name: Template SQM config
  template:
    src: "sqm.j2"
    dest: "{{source_dir}}/files/etc/config/sqm"

# Network and wifi stuff is hardware specific, so we keep templates for each
# supported device. it really shouldn't ever change much in upstream LEDE
# but do remember it's possible
- name: Template network interface configuration
  template:
    src: "{{conf_to_build}}-network.j2"
    dest: "{{source_dir}}/files/etc/config/network"

# Light client (phone) bootstrap network, used for phones to connect and open per-hop tunnels
# once a tunnel is opened they are attached to a Rita created and managed bridge which nats
# the traffic out the door
- name: Insert Phone bootstrap network
  blockinfile:
    insertbefore: BOF
    path: "{{source_dir}}/files/etc/config/network"
    block: |
      config interface 'pbs'
          option type 'bridge'
          option ifname 'pbs'
          option proto 'static'
          option ipaddr '{{pbs_ip}}'
          option netmask '255.255.255.0'
          option ip6assign '60'

- name: Insert Lan network
  blockinfile:
    insertbefore: BOF
    path: "{{source_dir}}/files/etc/config/network"
    block: |
      config interface 'lan'
          option type 'bridge'
          option ifname '{{lan_interfaces}}'
          option proto 'static'
          option ipaddr '{{lan_ip}}'
          option netmask '255.255.255.0'
          option ip6assign '60'

# we insert boilerplate stuff into the network configs here for the sake of de-duplication
- name: Insert Loopback network
  blockinfile:
    insertbefore: BOF
    path: "{{source_dir}}/files/etc/config/network"
    block: |
      config interface 'loopback'
          option ifname 'lo'
          option proto 'static'
          option ipaddr '127.0.0.1'
          option netmask '255.0.0.0'

- name: Template wifi interface configuration
  template:
    src: "{{conf_to_build}}-wireless.j2"
    dest: "{{source_dir}}/files/etc/config/wireless"
  when: wireless_conf_path is file

- name: Insert Mesh interface for radio0
  blockinfile:
    insertbefore: BOF
    dest: "{{source_dir}}/files/etc/config/wireless"
    block: |
      config wifi-iface 'mesh'
          option device 'radio0'
          option network 'rita_mesh'
          option mode 'mesh'
          option mesh_id 'AltheaMesh'
          option ssid 'AltheaMesh'
          option encryption 'none'
          option mesh_fwding '0'
          option ifname 'mesh'
          option disabled '1'
  when: wireless_conf_path is file

- name: Insert Light client interface for radio0
  blockinfile:
    insertbefore: BOF
    dest: "{{source_dir}}/files/etc/config/wireless"
    block: |
      config wifi-iface 'lightclient'
          option device 'radio0'
          option network 'pbs'
          option mode 'AP'
          option ssid 'AltheaPhone'
          option encryption 'none'
          option mesh_fwding '0'
          option ifname 'pbs'
          option disabled '0'
  when: wireless_conf_path is file

- name: Template the Babeld configuration
  template:
    src: "babeld.j2"
    dest: "{{source_dir}}/files/etc/config/babeld"

- name: Template the Rita configuration
  template:
    src: "rita.toml.j2"
    dest: "{{source_dir}}/files/etc/rita.toml"

- name: Write out build details
  template:
    src: "althea-firmware-release.j2"
    dest: "{{source_dir}}/files/etc/althea-firmware-release"

- name: Template package update url
  template:
    src: customfeeds.conf.j2
    dest: "{{source_dir}}/files/etc/opkg/customfeeds.conf"
