---
# Builds the more sensitive and dynamic parts of the firmware root configuration
# for example ssh keys are inserted in this role

- name: Create Dropbear folder
  file:
    path: "{{source_dir}}/files/etc/dropbear/"
    state: directory

- name: Add keys to login
  lineinfile:
    dest: "{{source_dir}}/files/etc/dropbear/authorized_keys"
    line: "{{item}}"
    state: present
    create: yes
  with_items: "{{keys_to_insert}}"

- name: Authorized keys only readable by owner
  file:
    path: "{{source_dir}}/files/etc/dropbear/authorized_keys"
    mode: 0600

- name: Template dropbear config
  template:
    src: "dropbear.j2"
    dest: "{{source_dir}}/files/etc/config/dropbear"

- name: Add wan ssh rule
  blockinfile:
    path: "{{source_dir}}/files/etc/fongi/firewall"
    state: present
    block: |
      config rule
		option name		Allow-Dropbear
		option src		wan
		option proto		tcp
		option family		ipv6
		option dest_port	22
		option target		ACCEPT
  when: dropbear_wan_accessible

- name: Create Wireguard Config folder
  file:
    path: "{{source_dir}}/files/etc/config/"
    state: directory

# Network and wifi stuff is hardware specific, so we keep templates for each
# supported device. it really shouldn't ever change much
# but do remember it's possible
- name: Template network interface configuration
  template:
    src: "{{conf_to_build}}-network.j2"
    dest: "{{source_dir}}/files/etc/config/network"

- name: Template wifi interface configuration
  template:
    src: "{{conf_to_build}}-wireless.j2"
    dest: "{{source_dir}}/files/etc/config/wireless"

- name: Template the babeld configuration
  template:
    src: "babeld.j2"
    dest: "{{source_dir}}/files/etc/config/babeld"

- name: Write out build details
  template:
    src: "althea-firmware-release.j2"
    dest: "{{source_dir}}/files/etc/althea-firmware-release"


- name: Template bootstrapping script
  template:
    src: "setup.ash.j2"
    dest: "{{source_dir}}/files/etc/setup.ash"
